
export const trips = [
    {
        "id": "ind-001",
        "destination": "Goa",
        "category": "Beach",
        "season": "Summer Special",
        "mood": "Party",
        "isOffbeat": false,
        "regrets": "Crowded during peak season, humid weather.",
        "dates": "2026-11-15 to 2026-11-20",
        "budget": 15000,
        "image": "https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?auto=format&fit=crop&q=80&w=1000",
        "image2": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=80",
        "description": "Experience the sun, sand, and vibrant nightlife of India's favorite beach destination.",
        "duration": "6 Days",
        "rating": 4.8,
        "reviews": 560
    },
    {
        "id": "ind-002",
        "destination": "Manali",
        "category": "Mountain",
        "season": "Summer Special",
        "mood": "Adventure",
        "isOffbeat": false,
        "regrets": "Heavy snow can block roads in winter.",
        "dates": "2026-05-10 to 2026-05-16",
        "budget": 12000,
        "image": "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&q=80&w=1000",
        "image2": "https://images.unsplash.com/photo-1595846519845-68e298c2edd8?auto=format&fit=crop&w=1000&q=80",
        "description": "Adventure awaits in the snow-covered peaks and pine forests of the Himalayas.",
        "duration": "7 Days",
        "rating": 4.7,
        "reviews": 290
    },
    {
        "id": "ind-003",
        "destination": "Jaipur",
        "category": "Heritage",
        "season": "Winter Special",
        "mood": "Peace",
        "isOffbeat": false,
        "regrets": "Can get very hot in summer months.",
        "dates": "2026-10-05 to 2026-10-10",
        "budget": 18000,
        "image": "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&q=80&w=1000",
        "image2": "https://images.unsplash.com/photo-1524230572899-a752b3835840?auto=format&fit=crop&w=1000&q=80",
        "description": "Explore the majestic forts, palaces, and vibrant culture of the Pink City.",
        "duration": "6 Days",
        "rating": 4.9,
        "reviews": 410
    },
    {
        "id": "ind-004",
        "destination": "Varanasi",
        "category": "Spiritual",
        "season": "Winter Special",
        "mood": "Peace",
        "isOffbeat": false,
        "regrets": "Narrow streets can be overwhelming for some.",
        "dates": "2026-03-12 to 2026-03-16",
        "budget": 10000,
        "image": "https://images.unsplash.com/photo-1561359313-0639aad49ca6?auto=format&fit=crop&q=80&w=1000",
        "image2": "https://images.unsplash.com/photo-1518005020250-ee2f9f297068?auto=format&fit=crop&w=1000&q=80",
        "description": "Experience the spiritual essence of India on the banks of the sacred Ganges.",
        "duration": "5 Days",
        "rating": 4.6,
        "reviews": 340
    },
    {
        "id": "ind-005",
        "destination": "Munnar",
        "category": "Nature",
        "season": "Monsoon Special",
        "mood": "Relax",
        "isOffbeat": false,
        "regrets": "Misty roads require careful driving.",
        "dates": "2026-12-01 to 2026-12-05",
        "budget": 14000,
        "image": "https://images.unsplash.com/photo-1542401886-65d6c61db217?auto=format&fit=crop&q=80&w=1000",
        "image2": "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?auto=format&fit=crop&w=1000&q=80",
        "description": "Breathe in the fresh air of rolling tea plantations and misty hills.",
        "duration": "5 Days",
        "rating": 4.7,
        "reviews": 210
    },
    {
        "id": "ind-007",
        "destination": "Leh-Ladakh",
        "category": "Mountain",
        "season": "Spring Special",
        "mood": "Adventure",
        "isOffbeat": true,
        "regrets": "High altitude sickness is a common risk.",
        "dates": "2026-06-20 to 2026-06-28",
        "budget": 35000,
        "image": "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&q=80&w=1000",
        "description": "Discover the barren beauty and high-altitude monasteries of Ladakh.",
        "duration": "9 Days",
        "rating": 4.9,
        "reviews": 150
    },
    {
        "id": "ind-011",
        "destination": "Agra",
        "category": "Heritage",
        "season": "Winter Special",
        "mood": "Relax",
        "isOffbeat": false,
        "regrets": "Extremely crowded on weekends.",
        "dates": "2026-02-14 to 2026-02-16",
        "budget": 8000,
        "image": "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80&w=1000",
        "description": "Witness the eternal beauty of the Taj Mahal and the grandeur of the Mughal era.",
        "duration": "3 Days",
        "rating": 4.8,
        "reviews": 750
    },
    {
        "id": "ind-015",
        "destination": "Alleppey",
        "category": "Nature",
        "season": "Monsoon Special",
        "mood": "Relax",
        "isOffbeat": false,
        "regrets": "Mosquitoes can be an issue in backwaters.",
        "dates": "2026-11-20 to 2026-11-25",
        "budget": 18000,
        "image": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&q=80&w=1000",
        "description": "Cruise through the tranquil backwaters on a traditional houseboat stay.",
        "duration": "6 Days",
        "rating": 4.8,
        "reviews": 245
    },
    {
        "id": "ind-016",
        "destination": "Rishikesh",
        "category": "Spiritual",
        "season": "Summer Special",
        "mood": "Adventure",
        "isOffbeat": false,
        "regrets": "Water sports closed during monsoon.",
        "dates": "2026-04-10 to 2026-04-14",
        "budget": 16000,
        "image": "https://images.unsplash.com/photo-1592494804071-faea15d93a8a?auto=format&fit=crop&q=80&w=1000",
        "description": "Experience white-water rafting and spiritual serenity by the Ganges.",
        "duration": "5 Days",
        "rating": 4.8,
        "reviews": 320
    },
    {
        "id": "ind-017",
        "destination": "Udaipur",
        "category": "Heritage",
        "season": "Winter Special",
        "mood": "Relax",
        "isOffbeat": false,
        "regrets": "Palace entries can be expensive.",
        "dates": "2026-09-15 to 2026-09-19",
        "budget": 22000,
        "image": "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&q=80&w=1000",
        "description": "Immerse yourself in the royalty of the City of Lakes.",
        "duration": "5 Days",
        "rating": 4.9,
        "reviews": 415
    },
    {
        "id": "ind-018",
        "destination": "Andaman",
        "category": "Beach",
        "season": "Summer Special",
        "mood": "Relax",
        "isOffbeat": true,
        "regrets": "Limited mobile connectivity in remote islands.",
        "dates": "2026-12-10 to 2026-12-16",
        "budget": 45000,
        "image": "https://images.pexels.com/photos/1645028/pexels-photo-1645028.jpeg?auto=compress&cs=tinysrgb&w=1000",
        "description": "Relax on pristine white sands and explore vibrant coral reefs.",
        "duration": "7 Days",
        "rating": 4.9,
        "reviews": 180
    },
    {
        "id": "ind-019",
        "destination": "Hampi",
        "category": "Heritage",
        "season": "Winter Special",
        "mood": "Peace",
        "isOffbeat": true,
        "regrets": "Very rocky terrain, requires lot of walking.",
        "dates": "2026-01-20 to 2026-01-24",
        "budget": 12000,
        "image": "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&q=80&w=1000",
        "description": "Walk among the ancient ruins of the Vijayanagara Empire.",
        "duration": "5 Days",
        "rating": 4.8,
        "reviews": 295
    },
    {
        "id": "ind-021",
        "destination": "Kashmir",
        "category": "Mountain",
        "season": "Summer Special",
        "mood": "Relax",
        "isOffbeat": false,
        "regrets": "Occasional political instability impacts travel plans.",
        "dates": "2026-04-15 to 2026-04-22",
        "budget": 28000,
        "image": "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&q=80&w=1000",
        "description": "Experience the sheer beauty of Dal Lake and the snow-clad peaks of Gulmarg.",
        "duration": "8 Days",
        "rating": 4.9,
        "reviews": 840
    },
    {
        "id": "ind-022",
        "destination": "Madurai",
        "category": "Spiritual",
        "season": "Winter Special",
        "mood": "Peace",
        "isOffbeat": false,
        "regrets": "Very warm weather throughout the year.",
        "dates": "2026-02-10 to 2026-02-14",
        "budget": 12000,
        "image": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&q=80&w=1000",
        "description": "Visit the majestic Meenakshi Amman Temple and explore ancient Tamil culture.",
        "duration": "5 Days",
        "rating": 4.7,
        "reviews": 1250
    },
    {
        "id": "ind-023",
        "destination": "Jaisalmer",
        "category": "Adventure",
        "season": "Winter Special",
        "mood": "Adventure",
        "isOffbeat": true,
        "regrets": "Sandstorms can be unpredictable in the desert.",
        "dates": "2026-11-01 to 2026-11-06",
        "budget": 18000,
        "image": "https://images.pexels.com/photos/17236315/pexels-photo-17236315.jpeg?auto=compress&cs=tinysrgb&w=1000",
        "description": "Stay in the Golden Fort and experience a camel safari in the Thar Desert.",
        "duration": "6 Days",
        "rating": 4.8,
        "reviews": 670
    },
    {
        "id": "ind-024",
        "destination": "Kaziranga",
        "category": "Nature",
        "season": "Spring Special",
        "mood": "Adventure",
        "isOffbeat": true,
        "regrets": "Park closed during flood-prone monsoon months.",
        "dates": "2026-01-10 to 2026-01-15",
        "budget": 24000,
        "image": "https://images.unsplash.com/photo-1547970810-dc1eac37d174?auto=format&fit=crop&q=80&w=1000",
        "description": "Spot the rare one-horned rhinoceros in the wild wetlands of Assam.",
        "duration": "6 Days",
        "rating": 4.9,
        "reviews": 430
    },
    {
        "id": "ind-025",
        "destination": "Kochi",
        "category": "Heritage",
        "season": "Monsoon Special",
        "mood": "Party",
        "isOffbeat": false,
        "regrets": "Humidity can be taxing for sightseeing.",
        "dates": "2026-03-05 to 2026-03-09",
        "budget": 15000,
        "image": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&q=80&w=1200",
        "description": "Explore the colonial history and scenic backwaters of the Queen of Arabian Sea.",
        "duration": "5 Days",
        "rating": 4.6,
        "reviews": 890
    },
    {
        "id": "sea-008",
        "destination": "Cherrapunji",
        "category": "Nature",
        "season": "Monsoon Special",
        "mood": "Peace",
        "isOffbeat": true,
        "regrets": "Frequent heavy rains can limit outdoor activities.",
        "dates": "June - August",
        "budget": 25000,
        "image": "https://images.unsplash.com/photo-1433086966358-54859d0ed716?auto=format&fit=crop&q=80&w=1200",
        "description": "Visit the wettest place on earth for a dramatic and mystical monsoon experience.",
        "duration": "5 Days",
        "rating": 4.9,
        "reviews": 68
    },
    {
        "id": "sea-011",
        "destination": "Valley of Flowers",
        "category": "Nature",
        "season": "Spring Special",
        "mood": "Adventure",
        "isOffbeat": true,
        "regrets": "Strenuous trek required to reach the valley.",
        "dates": "July - August",
        "budget": 30000,
        "image": "https://images.pexels.com/photos/20803531/pexels-photo-20803531.jpeg?auto=compress&cs=tinysrgb&w=2000",
        "description": "Hike through a UNESCO site bursting with hundreds of species of wild alpine flowers.",
        "duration": "7 Days",
        "rating": 5.0,
        "reviews": 89
    },
    {
        "id": "off-001",
        "destination": "Spiti Valley",
        "category": "Mountain",
        "season": "Summer Special",
        "mood": "Adventure",
        "isOffbeat": true,
        "regrets": "Extremely cold temperatures even in summer nights.",
        "dates": "July - Sept",
        "budget": 35000,
        "image": "https://images.unsplash.com/photo-1542332213-31f87348057f?auto=format&fit=crop&q=80&w=1200",
        "description": "A high-altitude desert with stunning monasteries and rugged landscapes.",
        "duration": "10 Days",
        "rating": 4.9,
        "reviews": 120
    }
];
